apiVersion: harness.io/v1
kind: Component
type: service
identifier: sys_comp_07
name: sys_comp_07
owner: group:account/_test_underscore_group
spec:
  lifecycle: experimenta
  system:
  - system:account/Test_System_Git_Branch
metadata:
  description: Reporting analytics service
