apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_r
name: component_r
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: Config service component
