apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_f
name: component_f
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: Inventory tracking component
