apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_m
name: component_m
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: Search service component
