apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_d
name: component_d
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: User management component
