apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_h
name: component_h
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: Frontend web application
