apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_t
name: component_t
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: Monitoring service component
