apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_g
name: component_g
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: Reporting analytics component
