apiVersion: harness.io/v1
kind: Component
type: service
identifier: component_p
name: component_p
owner: user:your_user
spec:
  lifecycle: production
metadata:
  description: Logging service component
