apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: techdocs-enabled-template
  title: Template with TechDocs 1
  description: A Backstage template that is itself documented with TechDocs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user:guest
  type: template

  parameters:
    - title: Provide component details
      required:
        - name
      properties:
        name:
          type: string
        owner:
          type: string

  steps:
    - id: fetch-base
      name: Fetch base skeleton
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: .
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: register
      name: Register the component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['fetch-base'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Open in catalog
        url: ${{ steps.register.output.entityRef | entityRefToUrl }}
