apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: my-SErvice
  description: A sample service with TechDocs support
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-a
